---
- name: install openjdk 7
  apt: pkg=openjdk-7-jdk state=present
  sudo: yes

- name: install zookeeper
  apt: pkg=zookeeperd state=present
  sudo: yes

- name: install python-setuptools
  apt: pkg=python-setuptools state=present
  sudo: yes

- name: install python-protobuf
  apt: pkg=python-protobuf state=present
  sudo: yes
