---
- name: download mesos
  get_url: url=http://downloads.mesosphere.io/master/ubuntu/14.04/mesos_0.21.1-1.1.ubuntu1404_amd64.deb dest={{ install_dir }}/mesos-0.21.1.deb

- name: start create mesos upstart
  shell: dpkg -i {{ install_dir }}/mesos-0.21.1.deb;sudo touch {{ install_dir }}/opt2/mesos-deb-0.21.1.init creates={{ install_dir }}/opt2/mesos-deb-0.21.1.init
  sudo: yes

- name: fix apt-get
  shell: apt-get -f -y install
  sudo: yes

- name: mkdir mesos-slave directory
  template: src=mesos-slave.conf.j2 dest=/etc/init/mesos-slave.conf
  sudo: yes

- name: create mesos zookeeper list
  template: src=zookeeper-hosts.j2 dest=/etc/mesos/zk
  sudo: yes

- name: mkdir mesos url directory
  command: mkdir -p /etc/mesos
  sudo: yes

- name: mkdir mesos-slave directory
  command: mkdir -p /etc/mesos-slave
  sudo: yes

- name: start haproxy
  service: name=haproxy state=started
  ignore_errors: true
  sudo: yes
