---
- name: download mesos
  get_url: url=http://downloads.mesosphere.io/master/ubuntu/14.04/mesos_0.19.0~ubuntu14.04%2B1_amd64.deb dest={{ install_dir }}/mesos.deb

- name: start create mesos upstart
  shell: dpkg -i {{ install_dir }}/mesos.deb;sudo touch {{ install_dir }}/opt2/mesos-deb.init creates={{ install_dir }}/opt2/mesos-deb.init
  sudo: yes

- name: mkdir mesos-slave directory
  template: src=mesos-slave.conf.j2 dest=/etc/init/mesos-slave.conf
  sudo: yes

- name: create mesos zookeeper list
  template: src=zookeeper-hosts.j2 dest=/etc/mesos/zk

- name: mkdir mesos url directory
  command: mkdir -p /etc/mesos

- name: mkdir mesos-slave directory
  command: mkdir -p /etc/mesos-slave

- name: add deimos containerizer for mesos
  copy: src=deimos.cfg dest=/etc/deimos.cfg
  sudo: yes

- name: add deimos slave isolation for mesos
  copy: src=isolation.txt dest=/etc/mesos-slave/isolation
  sudo: yes

- name: switch zookeeper to manaual
  copy: src=manual.txt dest=/etc/init/zookeeper.override
  sudo: yes

- name: switch mesos-master to manaual
  copy: src=manual.txt dest=/etc/init/mesos-master.override
  sudo: yes

- name: switch mesos-slave to manaual
  copy: src=manual.txt dest=/etc/init/mesos-slave.override
  sudo: yes

- name: switch marathon to manaual
  copy: src=manual.txt dest=/etc/init/marathon.override
  sudo: yes

- name: download marathon
  get_url: url=http://downloads.mesosphere.io/marathon/marathon-0.6.0/marathon-0.6.0.tgz dest={{ install_dir }}/marathon-0.6.0.tgz

- name: unzip marathon
  command: tar xzf marathon-0.6.0.tgz chdir={{ install_dir }} creates={{ install_dir }}/marathon-0.6.0
